apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: first-pool
      protocol: layer2       # Use 'layer2' for simple IP allocation, or 'bgp' for more advanced setups
      addresses:
      - 165.232.88.120-165.232.88.130  # Modify this range according to your available IPs
